var armorLootTables = {
    "Light": {
        "Padded": 1,
        "Leather": 1,
        "Studded leather": 1
    },
    "Medium": {
        "Hide": 1,
        "Chain shirt": 1,
        "Scale mail": 1,
        "Breastplate": 1,
        "Half plate": 1
    },
    "Heavy": {
        "Ring mail": 1,
        "Chain mail": 1,
        "Splint": 1,
        "Plate": 1
    }
}

var weaponLootTables = {
    "Simple melee": {
        "Club": 1,
        "Dagger": 1,
        "Greatclub": 1,
        "Handaxe": 1,
        "Javelin": 1,
        "Light hammer": 1,
        "Mace": 1,
        "Quaterstaff": 1,
        "Sickle": 1,
        "Spear": 1
    },
    "Martial melee": {
        "Battleaxe": 1,
        "Flail": 1,
        "Glaive": 1,
        "Greataxe": 1,
        "Greatsword": 1,
        "Hallberd": 1,
        "Lance": 1,
        "Longsword": 1,
        "Maul": 1,
        "Morningstar": 1,
        "Pike": 1,
        "Rapier": 1,
        "Scimitar": 1,
        "Shortsword": 1,
        "Trident": 1,
        "War pick": 1,
        "Warhammer": 1,
        "Whip": 1
    },
    "Simple range": {
        "Crossbox, light": 1,
        "Dart": 1,
        "Shortbow": 1,
        "Sling": 1
    },
    "Martial range": {
        "Blowgun": 1,
        "Crossbox, hand": 1,
        "Crossbox, heavy": 1,
        "Longbow": 1,
        "Net": 1
    }
}

var offHandLootTables = {
    "Simple melee": {
        "Club": 1,
        "Dagger": 1,
        "Handaxe": 1,
        "Light hammer": 1,
        "Sickle": 1
    },
    "Martial melee": {
        "Scimitar": 1,
        "Shortsword": 1
    },
    "Martial range": {
        "Crossbox, hand": 1
    },
    "Armor": {
        "Shield": 1
    }
}

var magicLootTables = {
    "Minor Common": {
        "Potion of healing": 50,
        "Spell scroll (cantrip)": 10,
        "Potion of climbing": 10,
        "Spell scroll (1st level)": 20,
        "Spell scroll (2nd level)": 4,
        "Potion of greater healing": 4,
        "Bag of holding": 1,
        "Driftglobe": 1
    },
    "Minor Uncommon": {
        "Potion of greater healing": 15,
        "Potion of fire breath": 7,
        "Potion of resistance": 7,
        "Ammunition, +1": 5,
        "Potion of animal friendship": 5,
        "Potion of hill giant strength": 5,
        "Potion of growth": 5,
        "Potion of water breathing": 5,
        "Spell scroll (2nd level)": 5,
        "Spell scroll (3rd level)": 5,
        "Bag of holding": 3,
        "Keoghtom's ointment": 3,
        "Oil of slipperiness": 3,
        "Dust of disappearance": 2,
        "Dust of dryness": 2,
        "Dust of sneezing and choking": 2,
        "Elemental gem": 2,
        "Philter of love": 2,
        "Alchemy jug": 1,
        "Cap of water breathing": 1,
        "Cloak of the manta ray": 1,
        "Driftglobe": 1,
        "Goggles of night": 1,
        "Helm of comprehending languages": 1,
        "Immovable rod": 1,
        "Lantern of revealing": 1,
        "Mariner's armor": 1,
        "Mithral armor": 1,
        "Potion of poison": 1,
        "Ring of swimming": 1,
        "Robe of useful items": 1,
        "Rope of climbing": 1,
        "Saddle of the cavalier": 1,
        "Wand of magic detection": 1,
        "Wand of secrets": 1
    },
    "Minor Rare": {
        "Potion of superior healing": 15,
        "Spell scroll (4thlevel)": 7,
        "Ammunition, +2": 5,
        "Potion of clairvoyance": 5,
        "Potion of diminution": 5,
        "Potion of gaseous form": 5,
        "Potion of frost giant strength": 5,
        "Potion of stone giant strength": 5,
        "Potion of heroism": 5,
        "Potion of invulnerability": 5,
        "Potion of mind reading": 5,
        "Spell scroll (5thlevel)": 5,
        "Elixir of health": 3,
        "Oil of etherealness": 3,
        "Potion of fire giant strength": 3,
        "Quaal's feather token": 3,
        "Scroll of protection": 3,
        "Bag of beans": 2,
        "Bead of force": 2,
        "Chime of opening": 1,
        "Decanter of endless water": 1,
        "Eyes of minute seeing": 1,
        "olding boat": 1,
        "Heward's handy haversack": 1,
        "Horseshoes of speed": 1,
        "Necklace of fireballs": 1,
        "Periapt of health": 1,
        "Sending Stones": 1
    },
    "Minor Very Rare": {
        "Potion of supreme healing": 20,
        "Potion of invisibility": 10,
        "Potion of speed": 10,
        "Spell scroll (6thlevel)": 10,
        "Spell scroll (7thlevel)": 7,
        "Ammunition, +3": 5,
        "Oil of sharpness": 5,
        "Potion of flying": 5,
        "Potion of cloud giant strength": 5,
        "Potion of longevity": 5,
        "Potion of vitality": 5,
        "Spell scroll (8thlevel)": 5,
        "Horseshoes of a zephyr": 3,
        "Nolzur's marvelous pigments": 3,
        "Bag of devouring": 1,
        "Portable hole": 1
    },
    "Minor Legendary": {
        "Spell scroll (8thlevel)": 30,
        "Potion of storm giant strength": 25,
        "Poti on of supreme healing": 15,
        "Spell scroll (9st level)": 15,
        "Universal solvent": 8,
        "Arrow of slaying": 5,
        "Sovereign glue": 2
    },
    "Major Uncommon": {
        "Weapon, +1": 15,
        "Shield,+ 1": 3,
        "Sentinel shield": 3,
        "Amulet of proof against detection and location": 2,
        "Boots of elvenkind": 2,
        "Boots of striding and springing": 2,
        "Bracers of archery": 2,
        "Brooch of shielding": 2,
        "Broom of flying": 2,
        "Cloak of elvenkind": 2,
        "Cloak of protection": 2,
        "Gauntlets of ogre power": 2,
        "Hat of disguise": 2,
        "Javelin of lightning": 2,
        "Pearl of power": 2,
        "Rod of the pact keeper, + 1": 2,
        "Slippers of spider climbing": 2,
        "Staff of the adder": 2,
        "Staff of the python": 2,
        "Sword of vengeance": 2,
        "Trident of fish command": 2,
        "Wand of magic missiles": 2,
        "Wand of the war mage, + 1": 2,
        "Wand of web": 2,
        "Weapon of warning": 2,
        "Adamantine armor (chain mail)": 1,
        "Adamantine armor (chain shirt)": 1,
        "Adamantine armor (scale mail)": 1,
        "Bag of tricks (gray)": 1,
        "Bag of tricks (rust)": 1,
        "Bag of tricks (tan)": 1,
        "Boots of the winterlands": 1,
        "Circlet of blasting": 1,
        "Deck of illusions": 1,
        "Eversmoking bottle": 1,
        "Eyes of charming": 1,
        "Eyes of the eagle": 1,
        "igurine of wondrous power (silver raven)": 1,
        "Gem of brightness": 1,
        "Gloves of missile snaring": 1,
        "Gloves of swimming and climbing": 1,
        "Gloves of thievery": 1,
        "Headband of intellect": 1,
        "Helm of telepathy": 1,
        "nstrument of the bards (Doss lute)": 1,
        "nstrument of the bards (Fochlucan bandore)": 1,
        "nstrument of the bards (Mac-Fuimidh cittern)": 1,
        "Medallion of thoughts": 1,
        "Necklace of adaptation": 1,
        "Periapt of wound closure": 1,
        "Pipes of haunting": 1,
        "Pipes of the sewers": 1,
        "Ring of jumping": 1,
        "Ring of mind shielding": 1,
        "Ring of warmth": 1,
        "Ring of water walking": 1,
        "Quiver of Ehlonna": 1,
        "Stone of good luck": 1,
        "Wind fan": 1,
        "Winged boots": 1
    },
    "Major Rare": {
        "Weapon, +2": 11,
        "Figurine of wondrous power (Bronze griffon)": 3/8,
        "Figurine of wondrous power (Ebony fly)": 3/8,
        "Figurine of wondrous power (Golden lions)": 3/8,
        "Figurine of wondrous power (Ivory goats)": 3/8,
        "Figurine of wondrous power (Marble elephant)": 3/8,
        "Figurine of wondrous power (Onyx dog)": 6/8,
        "Figurine of wondrous power (Serpentine owl)": 3/8,
        "Adamantine armor (breastplate)": 1,
        "Adamantine armor (splint)": 1,
        "Amulet of health": 1,
        "Armor of vulnerability": 1,
        "Arrow-catching shield": 1,
        "Belt of dwarvenkind": 1,
        "Belt of hill giant strength": 1,
        "Berserker axe": 1,
        "Boots of levitation": 1,
        "Boots of speed": 1,
        "Bowl of commanding water elementals": 1,
        "Bracers of defense": 1,
        "Brazier of commanding fire elementals": 1,
        "Cape of the mountebank": 1,
        "Censer of controlling air elementals": 1,
        "Armor, +1 chain mail": 1,
        "Armor of resistance (chain mail)": 1,
        "Armor of resistance (chain shirt)": 1,
        "Armor,+ 1 chain shirt": 1,
        "Cloak of displacement": 1,
        "Cloak of the bat": 1,
        "Cube of force": 1,
        "Daern's instant fortress": 1,
        "Dagger of venom": 1,
        "Dimensional shackles": 1,
        "Dragon slayer": 1,
        "Elven chain": 1,
        "Flame tongue": 1,
        "Gem of seeing": 1,
        "Giant slayer": 1,
        "Clamoured studded leather": 1,
        "Helm of teleportation": 1,
        "Horn of blasting": 1,
        "Horn of Valhalla (silver or brass)": 1,
        "Instrument of the bards (Canaithmandolin)": 1,
        "Instrument ofthe bards (Cii lyre)": 1,
        "loun stone (awareness)": 1,
        "loun stone (protection)": 1,
        "loun stone (reserve)": 1,
        "loun stone (sustenance)": 1,
        "Iron bands of Bilarro": 1,
        "Armor, + 1 leather": 1,
        "Armor of resistance (leather)": 1,
        "Mace of disruption": 1,
        "Mace of smiting": 1,
        "Mace of terror": 1,
        "Mantle of spell resistance": 1,
        "Necklace of prayer beads": 1,
        "Periapt of proof against poison": 1,
        "Ring of animal influence": 1,
        "Ring of evasion": 1,
        "Ring of feather falling": 1,
        "Ring of free action": 1,
        "Ring of protection": 1,
        "Ring of resistance": 1,
        "Ring of spell storing": 1,
        "Ring of the ram": 1,
        "Ring of X-ray vision": 1,
        "Robe of eyes": 1,
        "Rod of rulership": 1,
        "Rod of the pact keeper, +2": 1,
        "Rope of entanglement": 1,
        "Armor, +1 scale mail": 1,
        "Armor of resistance (scale mail)": 1,
        "Shield, +2": 1,
        "Shield of missile attraction": 1,
        "Staff of charming": 1,
        "Staff of healing": 1,
        "Staff of swarming insects": 1,
        "Staff of the woodlands": 1,
        "Staff of withering": 1,
        "Stone of controlling earthelementals": 1,
        "Sun blade": 1,
        "Sword of life stealing": 1,
        "Sword of wounding": 1,
        "Tentacle rod": 1,
        "Vicious weapon": 1,
        "Wand of binding": 1,
        "Wand of enemy detection": 1,
        "Wand of fear": 1,
        "Wand of fireballs": 1,
        "Wand of lightning bolts": 1,
        "Wand of paralysis": 1,
        "Wand of the war mage, +2": 1,
        "Wand of wonder": 1,
        "Wings of flying": 1
    },
    "Major Very Rare": {
        "Weapon, +3": 10,
        "Amulet of the planes": 2,
        "Carpet of flying": 2,
        "Crystal ball (very rare version)": 2,
        "Ring of regeneration": 2,
        "Ring of shooting stars": 2,
        "Ring of telekinesis": 2,
        "Robe of scintillating colors": 2,
        "Robe of stars": 2,
        "Rod of absorption": 2,
        "Rod of alertness": 2,
        "Rod of security": 2,
        "Rod of the pact keeper, +3": 2,
        "Scimitar of speed": 2,
        "Shield, +3": 2,
        "Staff of fire": 2,
        "Staff of frost": 2,
        "Staff of power": 2,
        "Staff of striking": 2,
        "Staff of thunder and lightning": 2,
        "Sword of sharpnes": 2,
        "Wand of polymorph": 2,
        "Wand of the war mage, + 3": 2,
        "Adamantine armor (half plate)": 1,
        "Adamantine armor (plate)": 1,
        "Animated shield": 1,
        "Belt of fire giant strength": 1,
        "Belt of frost (or stone) giant strength": 1,
        "Armor, + 1 breastplate": 1,
        "Armor of resistance (breastplate)": 1,
        "Candle of invocation": 1,
        "Armor, +2 chain mail": 1,
        "Armor, +2 chain shirt": 1,
        "Cloak of arachnida": 1,
        "Dancing sword": 1,
        "Demon armor": 1,
        "Dragon scale mail": 1,
        "Dwarven plate": 1,
        "Dwarven thrower": 1,
        "Efreeti bottle": 1,
        "Figurine of wondrous power (obsidian steed)": 1,
        "Frost brand": 1,
        "Helm of brilliance": 1,
        "Horn ofValhalla (bronze)": 1,
        "Instrument of the bards (Anstruthharp)": 1,
        "loun stone (absorption)": 1,
        "loun stone (agility)": 1,
        "loun stone (fortitude)": 1,
        "loun stone (insight)": 1,
        "loun stone (intellect)": 1,
        "loun stone (leadership)": 1,
        "loun stone (strength)": 1,
        "Armor, +2 leather": 1,
        "Manual of bodily health": 1,
        "Manual of gainful exercise": 1,
        "Manual of golems": 1,
        "Manual of quickness of action": 1,
        "Mirror of life trapping": 1,
        "Nine lives stealer": 1,
        "Oathbow": 1,
        "Armor, +2 scale mail": 1,
        "Spellguard shield": 1,
        "Armor, + 1 splint": 1,
        "Armor of resistance (splint)": 1,
        "Armor, + 1 studded leather": 1,
        "Armor of resistance (studded leather)": 1,
        "Tome of clear thought": 1,
        "Tome of leadership and influence": 1,
        "Tome of understanding": 1
    },
    "Major Legendary": {
        "Defender": 5,
        "Hammer of thunderbolts": 5,
        "Luck Blade": 5,
        "Sword of answering": 5,
        "Holy avenger": 3,
        "Ring of djinni summoning": 3,
        "Ring of invisibility": 3,
        "Ring of spell turning": 3,
        "Robe of the archmagi": 3,
        "Rod of lordly might": 3,
        "Vorpal sword": 3,
        "Belt of cloud giant strength": 2,
        "Armor, +2 breastplate": 2,
        "Armor, +3 chain mail": 2,
        "Armor, +3 chain shirt": 2,
        "Cloak of invisibility": 2,
        "Crystal ball (legendary version)": 2,
        "Armor, + 1 half plate": 2,
        "Iron flask": 2,
        "Armor, +3 leather": 2,
        "Armor, +1 plate": 2,
        "Robe of the archmagi": 2,
        "Rod of resurrection": 2,
        "Armor, +1 scale mail": 2,
        "Scarab of protection": 2,
        "Armor, +2 splint": 2,
        "Armor, +2 studded leather": 2,
        "Well of many worlds": 2,
        "Magic armor (+2 half plate)": 2/12,
        "Magic armor (+2 plate)": 2/12,
        "Magic armor (+3 studded leather)": 2/12,
        "Magic armor (+3 breastplate)": 2/12,
        "Magic armor (+3 splint)": 2/12,
        "Magic armor (+3 half plate)": 1/12,
        "Magic armor (+3 plate)": 1/12,
        "Apparatus of Kwalish": 1,
        "Armor of invulnerability": 1,
        "Belt of storm giant strength": 1,
        "Cubic gate": 1,
        "Deck of many things": 1,
        "Efreeti chain": 1,
        "Armor of resistance (half plate)": 1,
        "Horn ofValhalla (iron)": 1,
        "Instrument of the bards (OIIamh harp)": 1,
        "loun stone (greater absorption)": 1,
        "loun stone (mastery)": 1,
        "loun stone (regeneration)": 1,
        "Plate armor of etherealness": 1,
        "Plate armor of resistance": 1,
        "Ring of air elemental command": 1,
        "Ring of earthelemental command": 1,
        "Ring of fire elemental command": 1,
        "Ring of three wishes": 1,
        "Ring of water elemental command": 1,
        "Sphere of annihilation": 1,
        "Talisman of pure good": 1,
        "Talisman of the sphere": 1,
        "Talisman of ultimate evil": 1,
        "Tome of the stilled tongue": 1
    }
}